name: Run Python Test Script Every 15 Mintues

on:
  schedule:
    - cron: '0,15,30,45 11-22 * * 1-5'

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
       
      - name: Write service_account.json from secret
        run: echo "${{ secrets.SERVICE_ACCOUNT }}" | base64 --decode > service_account.json

      - name: Run GoogleRunner
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
        run: python GoogleRunner.py
